---
title: "re2_tests"
output: rmarkdown::html_vignette
description: >
  Some notes on testing.
vignette: >
  %\VignetteIndexEntry{re2_tests}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Correctness of R interface is tested using the C++ test suits that
came with Google's RE2 distribution. RInside (a package to embed R in
C++) is used to convert the backend of the tests to use R interface
(instead of C++ interface) to RE2 library.

Read further if you have the source code and wish to understand the
testing procedure.

Google's RE2 library is in src/re2google folder. Only minimal
modifications have been done (to adapt to the demands of 'R CMD
check'). Tests are in src/re2google/re2/testing folder. During
testing, this folder will be symlinked to tests/re2goolge_test folder
through a symlink farm. The files re2/re2.cc and re2/re2.h, which
provide interface (and front-end implementation) to RE2 library, are
replaced by their R (inside) equivalents tests/re2_R.cc and
tests/re2_R.h. When C++ tests call RE2 library functions (like
RE2::Match(), RE2::Replace(), etc.), the call is routed through the R
interface to corresponding R functions (like re2_match(),
re2_replace(), etc.). In essence, the call goes from C++ to R (using
RInside) and R to C++ (using Rcpp). Only one instance of embedded R
is used for a suite of tests.

Before running the tests, install re2 (see the makefile in
src/util). Also, install package RInside. To compile and run tests:

```
> cd re2/tests
> make test
```

You should see the following output:
```
obj/test/charclass_test                 PASS
obj/test/compile_test                   PASS
obj/test/filtered_re2_test              PASS
obj/test/mimics_pcre_test               PASS
obj/test/parse_test                     PASS
obj/test/possible_match_test            PASS
obj/test/re2_test                       PASS
obj/test/re2_arg_test                   PASS
obj/test/regexp_test                    PASS
obj/test/required_prefix_test           PASS
obj/test/search_test                    PASS
obj/test/set_test                       PASS
obj/test/simplify_test                  PASS
obj/test/string_generator_test          PASS
ALL TESTS PASSED.
```

These tests are not included in 'R CMD check'. They
take a long time to compile and run, which is against
the guidelines.

To run benchmark tests:
```
> cd re2/tests
> make benchlog
```
