# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

re2_capturing_group_names <- function(pattern) {
    .Call(`_re2_re2_capturing_group_names`, pattern)
}

re2_check_rewrite_string <- function(pattern, rewrite, ...) {
    more_options <- list(...)
    .Call(`_re2_re2_check_rewrite_string`, pattern, rewrite, more_options)
}

re2_extract <- function(x, pattern, rewrite, ...) {
    more_options <- list(...)
    .Call(`_re2_re2_extract`, x, pattern, rewrite, more_options)
}

re2_get_options <- function(re2ptr) {
    .Call(`_re2_re2_get_options`, re2ptr)
}

re2_global_replace <- function(x, pattern, rewrite, ...) {
    more_options <- list(...)
    .Call(`_re2_re2_global_replace`, x, pattern, rewrite, more_options)
}

re2_match <- function(x, pattern, ...) {
    more_options <- list(...)
    .Call(`_re2_re2_match`, x, pattern, more_options)
}

re2_max_submatch <- function(rewrite) {
    .Call(`_re2_re2_max_submatch`, rewrite)
}

re2_named_capturing_groups <- function(pattern) {
    .Call(`_re2_re2_named_capturing_groups`, pattern)
}

re2_number_of_capturing_groups <- function(pattern) {
    .Call(`_re2_re2_number_of_capturing_groups`, pattern)
}

re2_possible_match_range <- function(pattern, maxlen, ...) {
    more_options <- list(...)
    .Call(`_re2_re2_possible_match_range`, pattern, maxlen, more_options)
}

re2_quote_meta <- function(unquoted) {
    .Call(`_re2_re2_quote_meta`, unquoted)
}

re2_re2 <- function(pattern, ...) {
    more_options <- list(...)
    .Call(`_re2_re2_re2`, pattern, more_options)
}

re2_replace <- function(x, pattern, rewrite, ...) {
    more_options <- list(...)
    .Call(`_re2_re2_replace`, x, pattern, rewrite, more_options)
}

re2_rewrite <- function(pattern, rewrite, vec, veclen, ...) {
    more_options <- list(...)
    .Call(`_re2_re2_rewrite`, pattern, rewrite, vec, veclen, more_options)
}

